version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Ensures AWS CodeBuild uses Node.js 18
    commands:
      - echo "Navigating to backend folder"
      - cd backend || { echo "Backend folder missing"; exit 1; }
      - echo "Installing backend dependencies..."
      - npm install --legacy-peer-deps

  pre_build:
    commands:
      - echo "Preparing environment"
      - npm run lint || echo "Lint warnings detected, continuing..."

  build:
    commands:
      - echo "Running backend build"
      - npm run build || { echo "Build failed"; exit 1; }

  post_build:
    commands:
      - echo "Post-build phase"
      - cd ../frontend || { echo "Frontend folder missing"; exit 1; }
      - echo "Skipping AWS S3 sync since deployment is from Git."

artifacts:
  files:
    - '**/*'
  name: DevOpsAppArtifacts
